# Generated by Django 4.2.5 on 2023-09-22 07:51

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryPost',
            fields=[
                ('idDiary', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('slug', models.CharField(blank=True, max_length=400, unique=True)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 9, 22, 7, 51, 9, 992767, tzinfo=datetime.timezone.utc))),
                ('day_count', models.IntegerField(default=0)),
                ('plans', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='author.author')),
            ],
        ),
    ]
