# Generated by Django 4.2.5 on 2023-09-22 07:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diarypost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 22, 7, 51, 17, 938044, tzinfo=datetime.timezone.utc)),
        ),
    ]
