# Generated by Django 4.2.5 on 2023-09-22 07:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_alter_diarypost_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diarypost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 22, 7, 55, 59, 602324, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='diarypost',
            name='day_count',
            field=models.IntegerField(default=1),
        ),
    ]
