# Generated by Django 4.2.5 on 2023-09-23 11:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_alter_diarypost_date_alter_diarypost_day_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diarypost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 23, 11, 58, 21, 490685, tzinfo=datetime.timezone.utc)),
        ),
    ]
